from tkinter import*

def show(p):
    text= p.widget.cget("text")
    print(text)    
num= Tk()
num.geometry("375x500")
num.title("CALCULATOR")
gvalue= StringVar()

screen = Entry(num, font="magenta")
screen.pack(fill=X, ipady=8, padx=10, pady=8)
fr = Frame(num)
fr.pack()
bt = Button(fr, text="c", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="√", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="/", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="<-", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
fr = Frame(num)
fr.pack()
bt = Button(fr, text="7", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="8", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="9", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="*", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
fr = Frame(num)
fr.pack()
bt = Button(fr, text="4", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="5", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="6", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="-", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
fr = Frame(num)
fr.pack()
bt = Button(fr, text="1", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="2", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="3", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="+", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
fr = Frame(num)
fr.pack()
bt = Button(fr, text="!", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="0", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text=".", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
bt = Button(fr, text="=", padx=18, pady=15, font="serif")
bt.pack(side=LEFT, padx=19, pady=5)
num.mainloop()